name: Tests

on: push

jobs:
  test:
    strategy:
      matrix:
        include:
          - id: windows:12
            os: windows-latest
            node: 12
          - id: macos:14
            os: macos-latest
            node: 14
          - id: ubuntu:16
            os: ubuntu-latest
            node: 16
    runs-on: ${{ matrix.os }}
    needs: [strict, browser]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run test

  browser:
    runs-on: ubuntu-latest
    needs: strict
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: sudo apt-get install xvfb
    - run: npm i
    - run: xvfb-run --auto-servernum npm run browser

  strict:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
    - run: npm i
    - run: npm run lint
    - run: npm test
